# Generated by Django 4.2.3 on 2023-07-05 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productbrand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('short_description', models.CharField(db_index=True, max_length=360, null=True)),
                ('description', models.TextField(db_index=True, null=True)),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('is_delete', models.BooleanField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productbrand')),
                ('category', models.ManyToManyField(related_name='product_categories', to='product.productcategory')),
            ],
        ),
    ]
