# Generated by Django 4.2.3 on 2023-07-08 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_categories_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='caption',
            field=models.CharField(db_index=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='product.product'),
        ),
    ]
