# Generated by Django 4.2.3 on 2023-07-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_producttag_caption_alter_producttag_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='product.productcategory'),
        ),
    ]
